### ISSUE TITLE
9장에서 DATA가 deprecated 되었습니다.

### ISSUE THREAD

**Issue by Hysperion** [junsuk5/kotlin-android#13]
9장에서 코드를 다 치고 고치라고 한 부분들도 다 고쳤는데 안되네요...안되는 이유 보니깐 MainActivity에서 DATA가 deprecated 된거 때문인것 같은데 정확한 이유는 모르겠습니다... 이걸 어떻게 고쳐야 할까요?

**Comment by junsuk5** [comment]
고칠 방법을 찾아서 답변 드린다고 생각만 하다가 아직 답을 못 드린걸 이제 확인했습니다.
openFileDescriptor를 사용하는 방법으로 변경된 코드는 반영되어 있습니다.
