### ISSUE TITLE
7장 웹브라우저 오버라이드된 onBackPressed 질문

### ISSUE THREAD

**Issue by junmin-Chang** [junsuk5/kotlin-android#18]
오버라이드된 onBackPressed는 onCreate안에 onBackPressed()를 작성해서 호출도 안되었는데 어떻게 오버라이드만 해서 이 함수가 작동이 되는건가요?

**Comment by junsuk5** [comment]
onBackPressed는 뒤로 가기 키를 누르면 호출되는 함수라서 그렇습니다. onCreate도 직접 호출한 적 없지만 호출되는 것과 마찬가지 입니다.

**Comment by junmin-Chang** [comment]
그렇다면 override fun onCreateContextMenu() 또한 뷰를 꾹 누르게 되면 호출되는 함수여서 굳이 따로 호출하지 않아도 작동하는 것인가요? 제가 잘 이해한게 맞나요

**Comment by junsuk5** [comment]
네 맞습니다. 안드로이드 프레임워크라는건 이렇게 미리 정해진 동작들이 다 구현되어 있고 여기에 우리가 조금씩 코드를 첨가하는 것입니다.
