### ISSUE TITLE
7장 225페이지 질문있습니다

### ISSUE THREAD

**Issue by kim-kwanghoon** [junsuk5/kotlin-android#20]
R.id.action_send -> {
                sendSMS("031-123-4567", webView.url!!)   
====== 안드로이드가 시켜서 !!를 넣었더니 오류가 안나요 
                return true
            }
R.id.action_email -> {
                email("test@example.com", "좋은 사이트", webView.url!!)
====== 안드로이드가 시켜서 !!를 넣었더니 오류가 안나요 
                return true

R.id.action_share ->{
               share(webView.url)
====== 여기는 오류가나요 webView.url 의 빨간줄이갑니다
                return true
            }
R.id.action_browser ->{
                browse(webView.url)
====== 여기는 오류가나요 webView.url 의 빨간줄이갑니다
                return true
            }

타입 미스매치가 왜뜨는걸까요? 

C:\Users\kimkwanghoon\AndroidStudioProjects\MyWebBrowser\app\src\main\java\org\techtown\mywebbrowser\MainActivity.kt: (102, 22): Type mismatch: inferred type is String? but String was expected

**Comment by junsuk5** [comment]
타입이 맞지 않아서 생기는 문제입니다.
코틀린에서 String 과 String? 는 다른 타입입니다
책을 쓴 시점과 현재의 안드로이드나 라이브러리 코드가 변경되면서 발생하는데요. 앞으로도 버전이 올라가면서 이런 자잘한 변경은 계속 생기게 됩니다.
예를 들어 webView.url 의 타입이 예전엔 String 이었는데 지금은 String? 가 되었을 것 같습니다.
따라서 webView.url 이 null이 되지 않도록 강제로 !!를 붙이면 일단 간단하게 에러가 해결됩니다.

133페이지 null값이 아님을 보증(!!) 을 참고하시기 바랍니다.

**Comment by kim-kwanghoon** [comment]
감사합니다!

**Comment by ks58ks** [comment]
감사합니다🤓

2020년 12월 11일 (금) 오후 9:23, hoonkim <notifications@github.com>님이 작성:
