### ISSUE TITLE
285page ViewPage가 사라지고 ViewPage2로 변경되었습니다만 혹시 이렇게 처리하는 방법은 없나요?

### ISSUE THREAD

**Issue by kim-kwanghoon** [junsuk5/kotlin-android#21]
285page ViewPage가 사라지고 ViewPage2로 변경되었습니다만 혹시 이렇게 처리하는 방법은 없나요?

**Comment by junsuk5** [comment]
ViewPage2는 RecyclerView와 같은 방식입니다.
https://developer.android.com/training/animation/vp2-migration?hl=ko 를 참고해서 변경해 보셔도 좋을 듯 합니다.

**Comment by kim-kwanghoon** [comment]
감사합니다
